services:
  mysql:
    image: mysql:8.0
    env_file:
      - docker.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_HEALTHCHECK_USER}", "-p${MYSQL_HEALTHCHECK_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
